name: Go presubmit

on:
  push:
    branches:
      - default
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Go presubmit
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ['1.15']
        os: ['ubuntu-latest']
    - uses: actions/checkout@v2
    - uses: creachadair/go-presubmit-action@default
      with:
        go-test-cpu: 2
